### ISSUE TITLE
Certrificate files are re-generated on each Puppet run

### ISSUE THREAD

**Issue by bjvrielink** [sjors101/Puppet_CertificateDistribution#5]
At least on RHEL/CentOS 7, each time Puppet runs, I get a fresh set of certificates in /etc/pki/ca-trust/extracted.

This is because /usr/bin/update-ca-trust is a much simpler script on RHEL7 compared to RHEL6, only supporting the "extract" option (and silently ignoring all other options).

This causes the "onlyif" section of Exec['enable update-ca-trust'] to trigger the extraction of the certificates on each run.

Suggested fix: limit the Exec['enable update-ca-trust'] to only run on RHEL/CentOS 6, as ca-trust is already enabled (and cannot easily be disabled) on RHEL7.

**Comment by sjors101** [comment]
Thanks for your input @bjvrielink , i will upload an new version to the forge later today.
